apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment-2
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 10.0.0.11:5000/nginx:1.15
        ports:
        - containerPort: 80
